# Generated by Django 5.0.6 on 2025-01-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('topic', models.ManyToManyField(related_name='questions', to='contents.topic')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=15)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='question_media/')),
                ('section_order', models.PositiveIntegerField(blank=True, null=True)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='problems.question')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['section_order'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('solution_text', models.TextField()),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='solution_media/')),
                ('question_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution', to='problems.question')),
            ],
            options={
                'db_table': 'solution',
            },
        ),
    ]
