# Generated by Django 5.1.6 on 2025-02-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_solution_order_id_alter_solution_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='solution_image',
            new_name='solution_img',
        ),
    ]
