# Generated by Django 5.1.6 on 2025-02-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_solution_image_solution_solution_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='solution_img',
            new_name='solution_image',
        ),
    ]
