# Generated by Django 5.1.6 on 2025-02-28 01:51

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_rename_solution_img_solution_solution_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='solution_media/'),
        ),
    ]
