# Generated by Django 5.1.6 on 2025-02-28 02:07

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_solution_solution_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image_content',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='question_media/'),
        ),
    ]
