# Generated by Django 5.0.6 on 2025-01-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=30)),
                ('chapter_description', models.TextField()),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic_name', models.TextField()),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.chapter')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
